name: Build and Deploy to Netlify
on:
  push:
  pull_request:
steps:
  - name: Wait for Netlify Deploy
  uses: kukiron/wait-for-netlify-deploy@v1.2.1
  id: waitForDeployment
    with:
      site_name: ${{ secrets.NETLIFY_SITE_NAME }}
      pr_number: ${{ steps.findPR.outputs.pr }} # use for `e2e_tests` branch
      max_timeout: 300
    env:
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    timeout-minutes: 1
