# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for Netlify Deploy
        uses: kukiron/wait-for-netlify-deploy@v1.2.1
        id: waitForDeployment
        with:
          site_name: ${{ secrets.NETLIFY_SITE_NAME }}
          # pr_number: ${{ steps.findPR.outputs.pr }} # use for `e2e_tests` branch
          # pr_number: ${{ github.event.pull_request.number }} # use for `master` branch
          max_timeout: 300
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}